config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :blog_posts do
    resources :comments, only: :create
  end
  
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]
  
    def index
      @blog_posts = Blog.all
    end
  
    def show
        @blog_post = Blog.find(params[:id])
        @comment = Comment.new
      end

    def new
      @blog_post = Blog.new
    end
  
    def create
      @blog_post = current_user.blogs.build(blog_post_params)
      if @blog_post.save
        redirect_to blog_post_path(@blog_post)
      else
        render :new, status: :unprocessable_entity
      end
    end 
  
    def edit
    end
  
    def update
      if @blog_post.update(blog_post_params)
        redirect_to blog_post_path(@blog_post)
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @blog_post.destroy
      redirect_to root_path
    end
  
    private
  
    def blog_post_params
      params.require(:blog).permit(:title, :body)
    end
  
    def set_blog_post
      @blog_post = Blog.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  
    def authenticate_user!
      unless current_user
        redirect_to root_path
      end
    end
  
    def authorize_user!
      unless @blog_post.user == current_user
        redirect_to root_path
      end
    end
  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @blog_post = Blog.find(params[:blog_id])
    @comment = @blog_post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to blog_post_path(@blog_post), notice: 'Comment was successfully posted.'
    else
      redirect_to blog_post_path(@blog_post), alert: 'Failed to post comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post, url: @blog_post.new_record? ? blog_posts_path : blog_post_path(@blog_post) do |form| %>
    <% if @blog_post.errors.any? %>
      <div>
        <% @blog_post.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render 'form' %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>

<% @blog_posts.each do |blog_post| %>
    <div>
  <h2><%= link_to blog_post.title, blog_post_path(blog_post.id) %></h2>
  <p><%= blog_post.body %></p>
  </div>

<% end %>

app/views/blog_posts/new.html.erb
<h1> New Blog Post </h1>

<%= render partial:"form", locals: {blog_post:@blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>

<h2>Comments</h2>
<% if @blog_post.comments.any? %>
  <% @blog_post.comments.each do |comment| %>
    <div>
      <strong><%= comment.user.email %>:</strong>
      <p><%= comment.content %></p>

      
    </div>
    <hr>
  <% end %>
<% else %>
  <p>No comments yet. Be the first to comment!</p>
<% end %>

<h3>Add a Comment</h3>
<%= form_with url: blog_post_comments_path(@blog_post), local: true do |form| %>
<div>
    <%= form.text_area :content, placeholder: "Enter your comment" %>
  </div>
  <div>
    <%= form.submit 'Post Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog Post" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div>
        <% if user_signed_in? %>
          <%= link_to "Home", root_path %>
          <%= link_to "New Blog Post", new_blog_post_path %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete %>
        <% end %>

      </div>
    <%= yield %>
  </body>
</html>